<a href="https://colab.research.google.com/github/HasnatHridoy/BD-antibiotic-drug-market-analysis/blob/main/scraper_files/notebooks/Antibiotic_price_scraping_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install google-colab-selenium -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 47.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 499.2/499.2 kB 31.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 66.4 MB/s eta 0:00:00

In [ ]:
#this driver is specifically used for google colab
#please inintialize your driver properly if you want to run it locally
import google_colab_selenium as gs
driver = gs.Chrome()

In [ ]:
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

# -------------- Scraping part -----------------

In [ ]:
#link scraper function

def link_scraper(links):

  if isinstance(links, str):
    links = [links]

  linking = []

  for link in links:
    driver.get(link)
    print(f'working on {driver.current_url}')

    try:
      div_elements = wait.until(
          EC.presence_of_all_elements_located((By.CSS_SELECTOR, ".col-xs-12.col-sm-6 a"))
      )

      # Extract href
      for element in div_elements:
          linking.append(element.get_attribute("href"))

    except Exception as e:
      print(f"An error occurred while scraping links: {e}")

  return linking

In [ ]:
wait = WebDriverWait(driver, 10)

In [ ]:
try:

  driver.get("https://medex.com.bd/drug-classes")
  print(f"Successfully navigated to: {driver.current_url}")

except Exception as e:
    print(f"An error occurred: {e}")

Successfully navigated to: https://medex.com.bd/drug-classes

In [ ]:
try:
    # click antimicrobial button
    antibio_button = wait.until(
        EC.element_to_be_clickable((By.LINK_TEXT, "Antimicrobial drugs"))
    )

    antibio_button.click()

    url = driver.current_url
    print(f"Successfully navigated to: {driver.current_url}")


except Exception as e:
    print(f"An error occurred: {e}")

Successfully navigated to: https://medex.com.bd/drug-classes/3/antimicrobial-drugs

In [ ]:
links= link_scraper(url)

working on https://medex.com.bd/drug-classes/3/antimicrobial-drugs

In [ ]:
links

['https://medex.com.bd/drug-classes/50/drugs-for-bacterial-infections-anti-bacterial',
 'https://medex.com.bd/drug-classes/51/drugs-for-fungal-infections-anti-fungal',
 'https://medex.com.bd/drug-classes/52/drugs-for-helminthiasis-anti-helminthic',
 'https://medex.com.bd/drug-classes/53/drugs-for-protozoal-infections-anti-protozoal',
 'https://medex.com.bd/drug-classes/54/drugs-for-viral-infections-anti-viral']

In [ ]:
links_2 = link_scraper(links[0])

working on https://medex.com.bd/drug-classes/50/drugs-for-bacterial-infections-anti-bacterial

In [ ]:
links_2

['https://medex.com.bd/drug-classes/55/4-quinolone-preparations',
 'https://medex.com.bd/drug-classes/56/aminoglycosides',
 'https://medex.com.bd/drug-classes/58/anti-tubercular-antibiotics',
 'https://medex.com.bd/drug-classes/59/anti-tubercular-chemotherapeutics',
 'https://medex.com.bd/drug-classes/60/benzylpenicillin-phenoxymethyl-penicillin',
 'https://medex.com.bd/drug-classes/61/broad-spectrum-penicillins',
 'https://medex.com.bd/drug-classes/62/combined-anti-tubercular-preparations',
 'https://medex.com.bd/drug-classes/566/ear-anti-infectives-antiseptics',
 'https://medex.com.bd/drug-classes/565/eye-anti-infectives-antiseptics',
 'https://medex.com.bd/drug-classes/675/fifth-generation-cephalosporins',
 'https://medex.com.bd/drug-classes/63/first-generation-cephalosporins',
 'https://medex.com.bd/drug-classes/64/fourth-generation-cephalosporins',
 'https://medex.com.bd/drug-classes/648/glycopeptide',
 'https://medex.com.bd/drug-classes/68/intracellular-antibiotic',
 'https://medex.com.bd/drug-classes/65/long-acting-penicillin',
 'https://medex.com.bd/drug-classes/66/macrolides',
 'https://medex.com.bd/drug-classes/67/mecillinams',
 'https://medex.com.bd/drug-classes/610/other-antibacterial-preparation',
 'https://medex.com.bd/drug-classes/618/other-antibiotic',
 'https://medex.com.bd/drug-classes/69/other-beta-lactam-antibiotics',
 'https://medex.com.bd/drug-classes/71/penicillinase-resistant-penicillins',
 'https://medex.com.bd/drug-classes/72/second-generation-cephalosporins',
 'https://medex.com.bd/drug-classes/73/sulphonamides-trimethoprim',
 'https://medex.com.bd/drug-classes/74/tetracycline-group-of-drugs',
 'https://medex.com.bd/drug-classes/75/third-generation-cephalosporins']

In [ ]:
links_interm = link_scraper(links_2)

working on https://medex.com.bd/drug-classes/55/4-quinolone-preparations
working on https://medex.com.bd/drug-classes/56/aminoglycosides
working on https://medex.com.bd/drug-classes/58/anti-tubercular-antibiotics
working on https://medex.com.bd/drug-classes/59/anti-tubercular-chemotherapeutics
working on https://medex.com.bd/drug-classes/60/benzylpenicillin-phenoxymethyl-penicillin
working on https://medex.com.bd/drug-classes/61/broad-spectrum-penicillins
working on https://medex.com.bd/drug-classes/62/combined-anti-tubercular-preparations
working on https://medex.com.bd/drug-classes/566/ear-anti-infectives-antiseptics
working on https://medex.com.bd/drug-classes/565/eye-anti-infectives-antiseptics
working on https://medex.com.bd/drug-classes/675/fifth-generation-cephalosporins
working on https://medex.com.bd/drug-classes/63/first-generation-cephalosporins
working on https://medex.com.bd/drug-classes/64/fourth-generation-cephalosporins
working on https://medex.com.bd/drug-classes/648/glycopeptide
working on https://medex.com.bd/drug-classes/68/intracellular-antibiotic
working on https://medex.com.bd/drug-classes/65/long-acting-penicillin
working on https://medex.com.bd/drug-classes/66/macrolides
working on https://medex.com.bd/drug-classes/67/mecillinams
working on https://medex.com.bd/drug-classes/610/other-antibacterial-preparation
working on https://medex.com.bd/drug-classes/618/other-antibiotic
working on https://medex.com.bd/drug-classes/69/other-beta-lactam-antibiotics
working on https://medex.com.bd/drug-classes/71/penicillinase-resistant-penicillins
working on https://medex.com.bd/drug-classes/72/second-generation-cephalosporins
working on https://medex.com.bd/drug-classes/73/sulphonamides-trimethoprim
working on https://medex.com.bd/drug-classes/74/tetracycline-group-of-drugs
working on https://medex.com.bd/drug-classes/75/third-generation-cephalosporins

In [ ]:
links_interm

['https://medex.com.bd/generics/1164/betamethasone-phenylephrine-lignocaine',
 'https://medex.com.bd/generics/263/ciprofloxacin',
 'https://medex.com.bd/generics/1975/delafloxacin',
 'https://medex.com.bd/generics/1182/gemifloxacin',
 'https://medex.com.bd/generics/1313/levofloxacin-ophthalmic',
 'https://medex.com.bd/generics/680/levofloxacin-hemihydrate',
 'https://medex.com.bd/generics/693/lomefloxacin',
 'https://medex.com.bd/generics/1625/moxifloxacin-hydrochloride-injection',
 'https://medex.com.bd/generics/776/moxifloxacin-hydrochloride-tablet',
 'https://medex.com.bd/generics/836/ofloxacin',
 'https://medex.com.bd/generics/866/pefloxacin-mesylate-dihydrate',
 'https://medex.com.bd/generics/957/rifaximin',
 'https://medex.com.bd/generics/1012/sparfloxacin',
 'https://medex.com.bd/generics/54/amikacin',
 'https://medex.com.bd/generics/1505/gentamicin-sulfate-injection',
 'https://medex.com.bd/generics/1090/tobramycin-nebuliser-solution',
 'https://medex.com.bd/generics/956/rifampicin',
 'https://medex.com.bd/generics/438/ethambutol',
 'https://medex.com.bd/generics/881/phenoxymethyl-penicillin-penicillin-v',
 'https://medex.com.bd/generics/70/amoxicillin-clavulanic-acid',
 'https://medex.com.bd/generics/69/amoxicillin-trihydrate',
 'https://medex.com.bd/generics/890/piperacillin-tazobactam',
 'https://medex.com.bd/generics/636/rifampicin-isoniazid',
 'https://medex.com.bd/generics/439/rifampicin-isoniazid-pyrazinamide-ethambutol',
 'https://medex.com.bd/generics/237/chloramphenicol-ophthalmic',
 'https://medex.com.bd/generics/237/chloramphenicol-ophthalmic',
 'https://medex.com.bd/generics/851/oxytetracycline',
 'https://medex.com.bd/generics/2332/ceftaroline-fosamil',
 'https://medex.com.bd/generics/210/cefadroxil-monohydrate',
 'https://medex.com.bd/generics/1454/cefazolin-sodium',
 'https://medex.com.bd/generics/231/cephalexin',
 'https://medex.com.bd/generics/232/cephradine',
 'https://medex.com.bd/generics/215/cefepime-hydrochloride',
 'https://medex.com.bd/generics/1077/teicoplanin',
 'https://medex.com.bd/generics/2088/fosfomycin-sodium',
 'https://medex.com.bd/generics/1374/fosfomycin-trometamol',
 'https://medex.com.bd/generics/110/benzathine-penicillin',
 'https://medex.com.bd/generics/100/azithromycin-dihydrate',
 'https://medex.com.bd/generics/1865/azithromycin-dihydrate-ophthalmic',
 'https://medex.com.bd/generics/237/chloramphenicol-ophthalmic',
 'https://medex.com.bd/generics/1847/chloramphenicol-oral',
 'https://medex.com.bd/generics/271/clarithromycin',
 'https://medex.com.bd/generics/273/clindamycin',
 'https://medex.com.bd/generics/1588/clindamycin-lotion',
 'https://medex.com.bd/generics/1834/clindamycin-vaginal-cream',
 'https://medex.com.bd/generics/427/erythromycin-oral',
 'https://medex.com.bd/generics/508/fusidic-acid',
 'https://medex.com.bd/generics/688/linezolid',
 'https://medex.com.bd/generics/971/roxithromycin',
 'https://medex.com.bd/generics/1013/spectinomycin',
 'https://medex.com.bd/generics/1014/spiramycin',
 'https://medex.com.bd/generics/894/pivmecillinam',
 'https://medex.com.bd/generics/240/chlorhexidine-gluconate-02',
 'https://medex.com.bd/generics/1493/chlorhexidine-gluconate-1',
 'https://medex.com.bd/generics/1494/chlorhexidine-gluconate-4',
 'https://medex.com.bd/generics/1429/colistimethate-sodium',
 'https://medex.com.bd/generics/1664/dequalinium-chloride',
 'https://medex.com.bd/generics/1823/isopropyl-alcohol',
 'https://medex.com.bd/generics/2096/lefamulin-acetate',
 'https://medex.com.bd/generics/1817/polymyxin-b-sulfate',
 'https://medex.com.bd/drug-classes/619/other-antibiotic',
 'https://medex.com.bd/drug-classes/657/probiotic',
 'https://medex.com.bd/generics/101/aztreonam',
 'https://medex.com.bd/generics/388/doripenem',
 'https://medex.com.bd/generics/1262/ertapenem',
 'https://medex.com.bd/generics/255/imipenem-cilastatin',
 'https://medex.com.bd/generics/731/meropenem-trihydrate',
 'https://medex.com.bd/generics/890/piperacillin-tazobactam',
 'https://medex.com.bd/generics/292/cloxacillin-sodium',
 'https://medex.com.bd/generics/473/flucloxacillin-sodium',
 'https://medex.com.bd/generics/209/cefaclor-monohydrate',
 'https://medex.com.bd/generics/226/cefuroxime-axetil',
 'https://medex.com.bd/generics/1024/sulphamethoxazole-trimethoprim',
 'https://medex.com.bd/generics/394/doxycycline-hydrochloride',
 'https://medex.com.bd/generics/704/lymecycline',
 'https://medex.com.bd/generics/1601/minocycline-hydrochloride',
 'https://medex.com.bd/generics/851/oxytetracycline',
 'https://medex.com.bd/generics/1060/tetracycline-hydrochloride',
 'https://medex.com.bd/generics/1070/tigecycline',
 'https://medex.com.bd/generics/211/cefdinir',
 'https://medex.com.bd/generics/212/cefditoren',
 'https://medex.com.bd/generics/1415/cefoperazone-sodium',
 'https://medex.com.bd/generics/218/cefotaxime',
 'https://medex.com.bd/generics/220/cefpodoxime-proxetil',
 'https://medex.com.bd/generics/221/cefpodoxime-proxetil-clavulanic-acid',
 'https://medex.com.bd/generics/223/ceftazidime-pentahydrate',
 'https://medex.com.bd/generics/224/ceftibuten-dihydrate',
 'https://medex.com.bd/generics/225/ceftriaxone-sodium']

In [ ]:
#two links have sublinks, they need to extract separately
links_workable = links_interm.copy()
link_pop = []

for link in links_interm:

  if 'other-antibiotic' in link or 'probiotic' in link:
    link_pop.append(link)
    links_workable.remove(link)

In [ ]:
links_pop = link_scraper(link_pop)

working on https://medex.com.bd/drug-classes/619/other-antibiotic
working on https://medex.com.bd/drug-classes/657/probiotic

In [ ]:
links_workable.extend(links_pop)

In [ ]:
#some links have duplicate
from collections import Counter

item_counts = Counter(links_workable) #count

duplicates = [item for item, count in item_counts.items() if count > 1]

if duplicates:
  print("duplicates:")
  for duplicate in duplicates:
    print(duplicate)
else:
  print("Nill")

duplicates:
https://medex.com.bd/generics/890/piperacillin-tazobactam
https://medex.com.bd/generics/237/chloramphenicol-ophthalmic
https://medex.com.bd/generics/851/oxytetracycline

In [ ]:
links_workable = list(set(links_workable))

In [ ]:
len(links_workable)

98

In [ ]:
data_extract =[]

In [ ]:
try:

  for link in links_workable:

    parts = link.split('/')
    generic_name = parts[-1]

    driver.get(link+'/brand-names')
    print(f'working on {driver.current_url}')



    table = driver.find_element(By.CLASS_NAME, 'table.gg-table.bindex-table')
    rows = table.find_elements(By.TAG_NAME, 'tr')

    for row in rows:
      cells = row.find_elements(By.TAG_NAME, 'td')

      if not cells:
          continue

      brand_name = cells[0].text
      dosage_form = cells[1].text
      strength = cells[2].text
      company = cells[3].text
      price_pack = cells[4].text

      data_extract.append([generic_name, brand_name, dosage_form, strength, company, price_pack])

except Exception as e:
    print(f"An error occurred while scraping links: {e}")

working on https://medex.com.bd/generics/2088/fosfomycin-sodium/brand-names
working on https://medex.com.bd/generics/776/moxifloxacin-hydrochloride-tablet/brand-names
working on https://medex.com.bd/generics/69/amoxicillin-trihydrate/brand-names
working on https://medex.com.bd/generics/237/chloramphenicol-ophthalmic/brand-names
working on https://medex.com.bd/generics/225/ceftriaxone-sodium/brand-names
working on https://medex.com.bd/generics/1118/vancomycin-hydrochloride/brand-names
working on https://medex.com.bd/generics/211/cefdinir/brand-names
working on https://medex.com.bd/generics/231/cephalexin/brand-names
working on https://medex.com.bd/generics/1024/sulphamethoxazole-trimethoprim/brand-names
working on https://medex.com.bd/generics/1505/gentamicin-sulfate-injection/brand-names
working on https://medex.com.bd/generics/2310/bacillus-subtilis-hu58/brand-names
working on https://medex.com.bd/generics/971/roxithromycin/brand-names
working on https://medex.com.bd/generics/957/rifaximin/brand-names
working on https://medex.com.bd/generics/273/clindamycin/brand-names
working on https://medex.com.bd/generics/851/oxytetracycline/brand-names
working on https://medex.com.bd/generics/866/pefloxacin-mesylate-dihydrate/brand-names
working on https://medex.com.bd/generics/894/pivmecillinam/brand-names
working on https://medex.com.bd/generics/220/cefpodoxime-proxetil/brand-names
working on https://medex.com.bd/generics/255/imipenem-cilastatin/brand-names
working on https://medex.com.bd/generics/1910/colistin-sulfate-veterinary/brand-names
working on https://medex.com.bd/generics/508/fusidic-acid/brand-names
working on https://medex.com.bd/generics/881/phenoxymethyl-penicillin-penicillin-v/brand-names
working on https://medex.com.bd/generics/1374/fosfomycin-trometamol/brand-names
working on https://medex.com.bd/generics/1395/tedizolid-phosphate/brand-names
working on https://medex.com.bd/generics/1847/chloramphenicol-oral/brand-names
working on https://medex.com.bd/generics/2042/probiotic-combination-hn019-10-billion/brand-names
working on https://medex.com.bd/generics/70/amoxicillin-clavulanic-acid/brand-names
working on https://medex.com.bd/generics/731/meropenem-trihydrate/brand-names
working on https://medex.com.bd/generics/210/cefadroxil-monohydrate/brand-names
working on https://medex.com.bd/generics/2409/probiotic-prebiotic-vitamin-k2-7/brand-names
working on https://medex.com.bd/generics/1181/sodium-fusidate-oral/brand-names
working on https://medex.com.bd/generics/223/ceftazidime-pentahydrate/brand-names
working on https://medex.com.bd/generics/2332/ceftaroline-fosamil/brand-names
working on https://medex.com.bd/generics/1077/teicoplanin/brand-names
working on https://medex.com.bd/generics/1817/polymyxin-b-sulfate/brand-names
working on https://medex.com.bd/generics/1824/probiotic-combination-9-billion/brand-names
working on https://medex.com.bd/generics/956/rifampicin/brand-names
working on https://medex.com.bd/generics/388/doripenem/brand-names
working on https://medex.com.bd/generics/218/cefotaxime/brand-names
working on https://medex.com.bd/generics/1013/spectinomycin/brand-names
working on https://medex.com.bd/generics/1823/isopropyl-alcohol/brand-names
working on https://medex.com.bd/generics/1975/delafloxacin/brand-names
working on https://medex.com.bd/generics/1498/probiotic-combination-4-billion/brand-names
working on https://medex.com.bd/generics/439/rifampicin-isoniazid-pyrazinamide-ethambutol/brand-names
working on https://medex.com.bd/generics/836/ofloxacin/brand-names
working on https://medex.com.bd/generics/1601/minocycline-hydrochloride/brand-names
working on https://medex.com.bd/generics/2456/probiotic-combination-bi-07-10-billion/brand-names
working on https://medex.com.bd/generics/1070/tigecycline/brand-names
working on https://medex.com.bd/generics/271/clarithromycin/brand-names
working on https://medex.com.bd/generics/232/cephradine/brand-names
working on https://medex.com.bd/generics/1429/colistimethate-sodium/brand-names
working on https://medex.com.bd/generics/101/aztreonam/brand-names
working on https://medex.com.bd/generics/1494/chlorhexidine-gluconate-4/brand-names
working on https://medex.com.bd/generics/1625/moxifloxacin-hydrochloride-injection/brand-names
working on https://medex.com.bd/generics/1060/tetracycline-hydrochloride/brand-names
working on https://medex.com.bd/generics/693/lomefloxacin/brand-names
working on https://medex.com.bd/generics/292/cloxacillin-sodium/brand-names
working on https://medex.com.bd/generics/427/erythromycin-oral/brand-names
working on https://medex.com.bd/generics/100/azithromycin-dihydrate/brand-names
working on https://medex.com.bd/generics/680/levofloxacin-hemihydrate/brand-names
working on https://medex.com.bd/generics/1493/chlorhexidine-gluconate-1/brand-names
working on https://medex.com.bd/generics/110/benzathine-penicillin/brand-names
working on https://medex.com.bd/generics/263/ciprofloxacin/brand-names
working on https://medex.com.bd/generics/890/piperacillin-tazobactam/brand-names
working on https://medex.com.bd/generics/636/rifampicin-isoniazid/brand-names
working on https://medex.com.bd/generics/1474/bacillus-clausii-spores/brand-names
working on https://medex.com.bd/generics/688/linezolid/brand-names
working on https://medex.com.bd/generics/1182/gemifloxacin/brand-names
working on https://medex.com.bd/generics/2070/probiotic-combination-2-billion/brand-names
working on https://medex.com.bd/generics/704/lymecycline/brand-names
working on https://medex.com.bd/generics/1012/sparfloxacin/brand-names
working on https://medex.com.bd/generics/1588/clindamycin-lotion/brand-names
working on https://medex.com.bd/generics/215/cefepime-hydrochloride/brand-names
working on https://medex.com.bd/generics/394/doxycycline-hydrochloride/brand-names
working on https://medex.com.bd/generics/2298/saccharomyces-boulardii-lactobacillus-rhamnosus-zinc/brand-names
working on https://medex.com.bd/generics/1834/clindamycin-vaginal-cream/brand-names
working on https://medex.com.bd/generics/1876/probiotic-combination-14-strains/brand-names
working on https://medex.com.bd/generics/1014/spiramycin/brand-names
working on https://medex.com.bd/generics/438/ethambutol/brand-names
working on https://medex.com.bd/generics/2096/lefamulin-acetate/brand-names
working on https://medex.com.bd/generics/1262/ertapenem/brand-names
working on https://medex.com.bd/generics/2069/probiotic-combination-23-billion/brand-names
working on https://medex.com.bd/generics/1090/tobramycin-nebuliser-solution/brand-names
working on https://medex.com.bd/generics/221/cefpodoxime-proxetil-clavulanic-acid/brand-names
working on https://medex.com.bd/generics/473/flucloxacillin-sodium/brand-names
working on https://medex.com.bd/generics/1415/cefoperazone-sodium/brand-names
working on https://medex.com.bd/generics/1454/cefazolin-sodium/brand-names
working on https://medex.com.bd/generics/209/cefaclor-monohydrate/brand-names
working on https://medex.com.bd/generics/54/amikacin/brand-names
working on https://medex.com.bd/generics/1313/levofloxacin-ophthalmic/brand-names
working on https://medex.com.bd/generics/1865/azithromycin-dihydrate-ophthalmic/brand-names
working on https://medex.com.bd/generics/1614/probiotic-combination-20-billion/brand-names
working on https://medex.com.bd/generics/226/cefuroxime-axetil/brand-names
working on https://medex.com.bd/generics/212/cefditoren/brand-names
working on https://medex.com.bd/generics/1664/dequalinium-chloride/brand-names
working on https://medex.com.bd/generics/240/chlorhexidine-gluconate-02/brand-names
working on https://medex.com.bd/generics/224/ceftibuten-dihydrate/brand-names
working on https://medex.com.bd/generics/1164/betamethasone-phenylephrine-lignocaine/brand-names

In [ ]:
len(data_extract)

3521

In [ ]:
data_extract[0]

['fosfomycin-sodium',
 'Fosfomax',
 'IV Infusion',
 '4 gm/vial',
 'Square Pharmaceuticals PLC',
 '4 gm vial: ৳ 1,200.00']

#--------------------- Data Processing part -----------------------

In [ ]:
import re

In [ ]:
#striper function

def extract_price(text):
    #price_unit
    match = re.search(r'৳\s*([\d,.]+)', text)
    if match:
        return float(match.group(1).replace(',', ''))
    return None

def extract_strip_price(text):
    #strip price
    match = re.search(r'\([^)]*৳\s*([\d,.]+)\)', text)
    if match:
        return float(match.group(1).replace(',', ''))
    return None

def extract_pack_size(text):
    #pack

    # Case 1: "A x B" format
    match = re.search(r'\((\d+\s*x\s*\d+)', text)
    if match:
        return match.group(1).strip() + " pcs"

    # Case 2: numeric + unit format
    match = re.search(r"(\d+\s*[a-zA-Z/%']+)", text, re.IGNORECASE)
    if match:
        return match.group(1).strip()

    return None

def extract_pack_type(text):
    #pck_type

    match = re.search(r'\b(bottle|tube|sachet|vial|ampoule|refill|pack|drop)\b', text, re.IGNORECASE)
    if match:
        return match.group(1).lower()

    # If multiplicative pattern exists, assume strip
    if re.search(r'\d+\s*x\s*\d+', text):
        return "strip"

In [ ]:
# preprocessing main function
def process_data(data):
    processed = []
    for row in data:
        pack_price_text = row[5]

        price = extract_price(pack_price_text)
        strip_price = extract_strip_price(pack_price_text)
        pack_size = extract_pack_size(pack_price_text)
        pack_type = extract_pack_type(pack_price_text)

        processed.append(row + [price, strip_price, pack_size, pack_type])
    return processed

In [ ]:
un_list = data_extract.copy()

In [ ]:
pro_list = []

In [ ]:
for item in un_list:
  regular_info = item[:5]
  pack_price_str = item[5]

  if '\n' in pack_price_str:
    pp_entry = pack_price_str.split('\n')

    for entry in pp_entry:
      pro_list.append(regular_info + [entry])

  else:
    pro_list.append(item)

In [ ]:
final_data_2 = process_data(pro_list)

In [ ]:
column_names = ['generics', 'product_name', 'dosage_form', 'strength', 'company', 'ref_p&p', 'unit_price','strip_price','pack_size','pack_type']
df_2 = pd.DataFrame(final_data_2, columns=column_names)

In [ ]:
df_2.head()

,generics,product_name,dosage_form,strength,company,ref_p&p,unit_price,strip_price,pack_size,pack_type
0,fosfomycin-sodium,Fosfomax,IV Infusion,4 gm/vial,Square Pharmaceuticals PLC,"4 gm vial: ৳ 1,200.00",1200.0,NaN,4 gm,vial
1,moxifloxacin-hydrochloride-tablet,Avaflox,Tablet,400 mg,UniMed UniHealth Pharmaceuticals Ltd.,Unit Price: ৳ 70.00 (1 x 10: ৳ 700.00),70.0,700.0,1 x 10 pcs,strip
2,moxifloxacin-hydrochloride-tablet,Eramox,Tablet,400 mg,Beacon Pharmaceuticals PLC,Unit Price: ৳ 60.00 (1 x 10: ৳ 600.00),60.0,600.0,1 x 10 pcs,strip
3,moxifloxacin-hydrochloride-tablet,Flomox,Tablet,400 mg,OSL Pharma Limited,Unit Price: ৳ 50.00 (1 x 10: ৳ 500.00),50.0,500.0,1 x 10 pcs,strip
4,moxifloxacin-hydrochloride-tablet,Floromox,Tablet,400 mg,Ibn Sina Pharmaceuticals Ltd.,Unit Price: ৳ 40.00 (2 x 10: ৳ 800.00),40.0,800.0,2 x 10 pcs,strip

In [ ]:
df_2.drop(columns=['strip_price']).isnull().sum()

generics         0
product_name     0
dosage_form      0
strength         0
company          0
ref_p&p          0
unit_price       3
pack_size       35
pack_type       45
dtype: int64

In [ ]:
df = df_2.dropna(subset=[col for col in df_2.columns if col != 'strip_price']).reset_index(drop=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3651 entries, 0 to 3650
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   generics      3651 non-null   object
 1   product_name  3651 non-null   object
 2   dosage_form   3651 non-null   object
 3   strength      3651 non-null   object
 4   company       3651 non-null   object
 5   ref_p&p       3651 non-null   object
 6   unit_price    3651 non-null   float64
 7   strip_price   1711 non-null   float64
 8   pack_size     3651 non-null   object
 9   pack_type     3651 non-null   object
dtypes: float64(2), object(8)
memory usage: 285.4+ KB

In [ ]:
df = df.drop('ref_p&p', axis=1)

In [ ]:
df.head()

,generics,product_name,dosage_form,strength,company,unit_price,strip_price,pack_size,pack_type
0,fosfomycin-sodium,Fosfomax,IV Infusion,4 gm/vial,Square Pharmaceuticals PLC,1200.0,NaN,4 gm,vial
1,moxifloxacin-hydrochloride-tablet,Avaflox,Tablet,400 mg,UniMed UniHealth Pharmaceuticals Ltd.,70.0,700.0,1 x 10 pcs,strip
2,moxifloxacin-hydrochloride-tablet,Eramox,Tablet,400 mg,Beacon Pharmaceuticals PLC,60.0,600.0,1 x 10 pcs,strip
3,moxifloxacin-hydrochloride-tablet,Flomox,Tablet,400 mg,OSL Pharma Limited,50.0,500.0,1 x 10 pcs,strip
4,moxifloxacin-hydrochloride-tablet,Floromox,Tablet,400 mg,Ibn Sina Pharmaceuticals Ltd.,40.0,800.0,2 x 10 pcs,strip

In [ ]:
df.to_csv('extracted_data.csv', index=False)